default_install_hook_types:
- commit-msg
- pre-commit

repos:
- repo: local
  hooks:
  - id: check-local-against-remote
    name: Check local against remote
    description: >
      Check whether the current branch is up-to-date with the remote dev branch.
    entry: ./scripts/check-local-against-remote.sh
    language: script
    stages: [pre-commit]
  - id: format
    name: Format code
    description: >
      Format the code using poetry run poe format.
    entry: ./scripts/format.sh
    language: script
    stages: [pre-commit]
  - id: lint
    name: Lint code
    description: >
      Lint the code using poetry run poe lint.
    entry: ./scripts/lint.sh
    language: script
    stages: [pre-commit]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.6.0
  hooks:
  - id: commitizen
    name: Check commit message format
    description: >
      Check whether the current commit message follows commiting rules. Allow
      empty commit messages by default, because they typically indicate to Git
      that the commit should be aborted.
    entry: cz check
    args: [--allow-abort, --commit-msg-file]
    stages: [commit-msg]