name: Bump version

permissions:
  contents: write

runs:
  using: composite

  steps:
  - name: Bump version and create tag
    shell: bash
    run: |
      git config --global user.name "GitHub Actions"
      git config --global user.email "actions@github.com"
      cz bump --yes
      git push origin HEAD:dev
      git push --tags
