name: Bump version

permissions:
  contents: write

runs:
  using: composite

  steps:
  - name: Set up Python
    uses: ./.github/actions/setup-python

  - name: Install Commitizen
    shell: bash
    run: |
      pip install commitizen

  - name: Bump version and create tag
    shell: bash
    run: |
      git config --global user.name "GitHub Actions"
      git config --global user.email "actions@github.com"
      cz bump --yes
      cz changelog
      git push origin HEAD:${{ github.event.pull_request.head.ref }}
      git push --tags
