name: Lint

runs:
  using: composite
  steps:
  - name: Install the tools
    shell: bash
    run: |
      pip install black isort pylint pytest

  - name: Run isort
    shell: bash
    run: |
      isort --profile=black --settings-path=pyproject.toml src tests

  - name: Run black
    shell: bash
    run: |
      black --config=pyproject.toml src tests

  - name: Run pylint
    shell: bash
    run: |
      pylint --rcfile=pyproject.toml src tests