name: Lint

runs:
  using: composite
  steps:
  - name: Format the code
    shell: bash
    run: |
      poetry run poe format

  - name: Lint the code
    shell: bash
    run: |
      poetry run poe lint
