name: Check version bump

outputs:
  bump_needed:
    description: Whether a bump is needed
    value: ${{ steps.check_bump.outputs.bump_needed }}
  bump_output:
    description: The output of cz bump
    value: ${{ steps.check_bump.outputs.bump_output }}
  from_version:
    description: The version to bump from
    value: ${{ steps.check_bump.outputs.from_version }}
  to_version:
    description: The version to bump to
    value: ${{ steps.check_bump.outputs.to_version }}

runs:
  using: composite
  steps:
  - name: Check for bump
    id: check_bump
    shell: bash
    run: |
      echo "Running cz bump --yes --dry-run"
      bump_output=$(cz bump --yes --dry-run 2>&1)
      echo "Bump output:"
      echo "$bump_output"
      printf "%s\n" "$bump_output" >> bump-output.txt
      if echo "$bump_output" | grep -q '[NO_COMMITS_TO_BUMP]'; then
        echo "No commits to bump"
        echo "bump_needed=false" >> $GITHUB_OUTPUT
      elif [ $? -eq 0 ]; then
        echo "Bump needed"
        echo "bump_needed=true" >> $GITHUB_OUTPUT
        from_version=$(echo "$bump_output" | grep -oP 'version [0-9]+\.[0-9]+\.[0-9]+ → [0-9]+\.[0-9]+\.[0-9]+' | cut -d' ' -f2)
        to_version=$(echo "$bump_output" | grep -oP 'version [0-9]+\.[0-9]+\.[0-9]+ → [0-9]+\.[0-9]+\.[0-9]+' | cut -d' ' -f4)
        echo "from_version=$from_version" >> $GITHUB_OUTPUT
        echo "to_version=$to_version" >> $GITHUB_OUTPUT
      else
        echo "Error running cz bump"
        echo "bump_needed=false" >> $GITHUB_OUTPUT
      fi

  - name: Upload bump output file
    uses: actions/upload-artifact@v3
    with:
      name: bump-output
      path: bump-output.txt