name: Create .bitsrc file
description: Creates a .bitsrc file with environment-specific variables
runs:
  using: composite
  steps:
    - name: Set execute permissions for create-bitsrc.sh
      run: chmod +x .github/actions/create-bitsrc/create-bitsrc.sh

    - name: Create .bitsrc file
      shell: bash
      run: ./.github/actions/create-bitsrc/create-bitsrc.sh