name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: ./.github/actions/setup-python
  
    - name: Set up Poetry
      uses: ./.github/actions/setup-poetry

    - name: Build the package
      uses: ./.github/actions/build-package

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: ./.github/actions/setup-python

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Install Poe the Poet
      run: |
        poetry add --dev poethepoet
  
    - name: Lint
      uses: ./.github/actions/lint

  test:
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    
    - name: Install pdflatex
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-recommended

    - name: Install the package
      uses: ./.github/actions/install-package

    - name: Create .bitsrc file
      uses: ./.github/actions/create-bitsrc

    - name: Test
      uses: ./.github/actions/test
